### ISSUE TITLE
Screen freezes

### ISSUE THREAD

**Issue by pmasawe** [SafeExamBrowser/seb-mac#10] opened 2017-10-16 13:21 UTC
Hi!

Four of our students experienced their screens freezing, everything stopped working and they had to eventually shut down their computers in order to get back control. This happened after they had successfully provided the password for the Safe Exam Browser configuration file and logged into their school portal. So the Safe Exam Browser had at least been able to start. The affected versions are as follows:

Mac OS 10.11.6
SEB 2.1.2

Best regards,
Patrick

**Comment by danschlet** [comment] 2017-10-17 15:46
Unfortunately this kind of error report doesn't help us to find the reason of the problem. We need more details:

- What was freezing exactly? Were they still able to move the mouse cursor or was that frozen too?
- Was only the web site not reacting or SEB too? Were you still able to click the quit button or press Cmd+Q to display the quit password dialog or SEB didn't react to that anymore?
- Send us the log file(s) from the affected Macs, which can be found at this path:
The log is saved to the directory ~/Library/Logs/Safe Exam Browser/ which is also displayed in the Console app log list (from [manual](https://www.safeexambrowser.org/macosx/mac_usermanual_en.html#SecurityPane))
- Ideally you should first try to reproduce the issue on another Mac and if you succeed, provide us with a test account in your school portal so we can try to reproduce it ourselves.

**Comment by pmasawe** [comment] 2017-10-17 16:57
Yes thanks!
Yeah I know that my info is not that quite helpful but this is all I got so far and if I am able to provide more I will do. But now all of a sudden it works after one of the students upgraded to Mac OS 10.13, maybe it was only a one time accident. 

Thanks!
Patrick

**Comment by barrasroger** [comment] 2017-11-29 14:39
We had a similar expirience with this Version.
after entering the startpassword the SEB started and Freezed the OS. The student was able to move the mouse cursor but it was not possible to quit the SEB, not with the quit button nor with the "cmd Q".

The interesting part is it worked after the student entered the password in a different way like this:

The password was: startWI28

After entering the password with the last 2 letters ("**28**") with Caps lock active the browser started successfully without a freeze. May be there is a hidden dialog in the background, to which the user cannot switch?

The OS of the Mac was OSX El Capitan 10.11.5

**Comment by danschlet** [comment] 2017-11-30 15:01
Most probably in the latter case SEB the config file or seb(s) link was tripple/double clicked. Then two "open file/link" events are sent to SEB. The first one let's users enter the start exam (settings) password, but the second displays a modal dialog that starting an exam isn't allowed, because one is already running. Because of some timing issues, the modal dialog in this case is displayed in the background (which shouldn't happen, that's a bug). But the modal dialog prevents any interaction in SEB, like clicking on the quit button or pressing Cmd+Q.

The fix should be easy, SEB needs to ignore if there is more than one "open file/link" events directly after starting. I'll let you know when there is a bugfix version available for testing.

**Comment by danschlet** [comment] 2018-01-19 23:24
This issue might be solved by some fixes in the current preview version of SEB 2.1.3 for macOS, you can download and test it here: https://github.com/SafeExamBrowser/seb-testing/tree/master/mac/2.1.3

**Comment by danschlet** [comment] 2018-08-24 20:16
This issue is fixed in SEB 2.1.3, use the final release version.

**Closed by danschlet** 2018-08-24 20:16 UTC
