### ISSUE TITLE
Opening Web Inspector in SEB on mac

### ISSUE THREAD

**Issue by Spruce8913** [SafeExamBrowser/seb-mac#327] opened 2023-10-18 15:35 UTC
Simply put: how do you open Web Inspector? I tried right-click, ctrl+left-click, (as explained in the [manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html)), option-command-I and many other combinations. I checked in the preferences: web inspector was enabled, and right mouse click was also enabled.

I saw another [issue ](https://github.com/SafeExamBrowser/seb-mac/issues/159) about Web Inspector on mac, which was mac's fault and thus passed on. So is Web Inspector not available currently then?

**Comment by danschlet** [comment] 2023-10-19 09:41
The last post in the issue you mentioned explains the situation as it is still today. WebInspector is only available in the classic WebView, not in the modern WebView which SEB now mostly uses.

**Comment by danschlet** [comment] 2023-10-19 09:41
Closed as duplicate of https://github.com/SafeExamBrowser/seb-mac/issues/159.

**Closed by danschlet** 2023-10-19 09:41 UTC

**Comment by Spruce8913** [comment] 2023-10-19 11:45
Could the documentation be slightly adapted in that case? My apologies for not understanding the other issue.
