### ISSUE TITLE
Very slow JavaScript on iOS

### ISSUE THREAD

**Issue by neb2000** [SafeExamBrowser/seb-mac#45] opened 2020-01-06 22:44 UTC
Hi, we are using SEB for IOS 2.1.15, and it seems everything on webpages using JavaScript (especially buttons with onclick listeners) are extremely unresponsive. An example would be setting the URL to Google and search for calculator, and tapping the numeric buttons takes a long time to take effect. If you tap the screen too fast the web page will zoom in instead of triggering a click.

The same website performs normally using SEB for macOS.

Are we missing any settings? Could you advise on how to fix this issue please?

**Comment by danschlet** [comment] 2020-01-27 16:01
The problem is that SEB currently uses the classic UIWebView (WebKit 1), there JavaScript is less performant than with the newer WKWebView (WebKit 2) engine, which Safari uses. I confirmed that with the alternate iOS browser "iCab", where you can switch between the classic and the modern web browser engine. With the classic engine, the Google calculator behaves exactly like in SEB.

We will integrate the modern WKWebView browser engine in the next few months is SEB. Some current SEB features are not supported by WKWebView (for example the current way the Browser Exam and Config Key are transmitted to the assessment system), so we have to implement some major changes. That's why we couldn't switch to WKWebView earlier.

Until then I would try to use web applications with efficient JavaScript usage. For example I don't understand why a simple calculator is so slow, even with the classic web engine...

**Comment by M4THYOU** [comment] 2020-05-21 13:14
@danschlet what's the status on refactoring to WKWebView?

**Comment by danschlet** [comment] 2020-05-21 18:57
See our roadmap at https://safeexambrowser.org/about_roadmap_en.html

Currently SEB 3.0 containing WKWebView is scheduled for Q2, but it will probably be delayed to August because of the recent situation.

**Comment by danschlet** [comment] 2021-09-19 09:50
This should habe been fixed in SEB 3.0 for iOS, as long as the modern WebView is used (see settings restrictions in [release notes](https://safeexambrowser.org/ios/ios_release_notes_en.html)).

**Closed by danschlet** 2021-09-19 09:50 UTC
