### ISSUE TITLE
SEB , Smartschool & Bookwidgets : SEB crashes sometimes when using video. (Youtube)

### ISSUE THREAD

**Issue by kristofschool** [SafeExamBrowser/seb-mac#364] opened 2024-01-12 11:57 UTC
**Describe the bug**
Some students have the problem that SEB crashes (goes to the end-page) when pushing on the play-button  in the Bookwidget.  It's a Youtube-link. 

**To Reproduce**
Go to Smartschool and open the Bookwidget.  
Advance to de video in the Bookwidget and push the PLAY-button 
SEB closes the Bookwidget and goes to the endpage of SEB.  

**Expected behavior**
Video Plays and student can continue the Bookwidget.

**Version Information**
Please complete the following information: 
 - OS: iOS 17.2, iPad 9 
 - SEB Version 3.3

**Additional Context**
It sometimes happens (1 / 20 students) .

**Comment by danschlet** [comment] 2024-01-12 13:35
This is a duplicate of https://github.com/SafeExamBrowser/seb-mac/issues/350.

Please always check if there is already an issue for a problem before opening a new one.

**Closed by danschlet** 2024-01-12 13:35 UTC
Labels: duplicate
