### ISSUE TITLE
Can not access mic and Camera

### ISSUE THREAD

**Issue by shivamTST** [SafeExamBrowser/seb-mac#100] opened 2021-07-18 15:53 UTC
Under Safe Exam browser, I can not access the camera and microphone while taking an exam using the SEB . I have a Mac OS big Sur 11.4, Kindly help with the issue as soon as possible.

**Comment by danschlet** [comment] 2021-07-18 16:24
Duplicate of #66

**Closed by danschlet** 2021-07-18 16:24 UTC
