### ISSUE TITLE
Cannot enable 3rd party Application on Mac

### ISSUE THREAD

**Issue by Dilshard** [SafeExamBrowser/seb-mac#297] opened 2023-04-20 10:41 UTC
Third party application cannot be enabled in safe exam browser like MS Word, MS Excel etc..
I tried by adding values in many different ways to the fields given(Executable, Original Name, Identifier, path and etc.. ) nothing worked. But it works with Windows OS as tested.

**Comment by danschlet** [comment] 2023-04-20 14:06
[As mentioned in the manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html#PermittedProcessesSection), it's currently not supported to open third party applications in SEB for macOS. We will add support for this later this year. See [this issue] 
(https://github.com/SafeExamBrowser/seb-mac/issues/78) and this [discussion](https://github.com/SafeExamBrowser/seb-mac/discussions/281).

**Comment by danschlet** [comment] 2023-04-20 14:07
Duplicate of https://github.com/SafeExamBrowser/seb-mac/issues/78

**Closed by danschlet** 2023-04-20 14:07 UTC
Labels: duplicate, read the manual
