### ISSUE TITLE
SEB 3.3 for iOS crashes on movie and audio (sliders and buttons)

### ISSUE THREAD

**Issue by rataplanbe** [SafeExamBrowser/seb-mac#350] opened 2023-12-08 11:17 UTC
Hi, we are working with SEB 3.3 en iPads with iPadOS above 17.1.x,

Text-fields, checklist, ... working great.

But their are problems with movies en audioclips.

Students can push the play-button. If they click on the pause-button or they using the slider to scroll or rewind te movie the app is crashing.

**Comment by danschlet** [comment] 2023-12-08 13:50
- Please send SEB log files (in directory ~/Library/Logs/Safe Exam Browser/ on Mac, use Settings app / SEB / Initiate Sending Logs to email log files to yourself and attach them here). 
- On iOS, please activate Settings / Privacy & Security / Share iPad Analytics / Share With App Developers, especially if you observed SEB crashes. We then receive anonymized crash reports. 
- Often a test link (send URL and if necessary login/password for a testing/demo account) or an SEB configuration file to reproduce the issue is helpful (remove SEB Quit and Admin passwords!) and compress the .seb file to ZIP to attach here.

**Comment by rataplanbe** [comment] 2023-12-11 17:33
Hi,I changed the settings for the log on 3 devices and realised crashes.In attachment, you can find a demo exam with an Youtube movie and a couple of questions.When opening with SEB, and moving the slider, on the youtube movie, the app crashes.The startcode is ‘comein’, the exit code is ‘exit’, without the quotes.Kind regards,Philip EveraertsOp 8 dec 2023 om 14:51 heeft Daniel R. Schneider ***@***.***> het volgende geschreven:﻿

Please send SEB log files (in directory ~/Library/Logs/Safe Exam Browser/ on Mac, use Settings app / SEB / Initiate Sending Logs to email log files to yourself and attach them here).
On iOS, please activate Settings / Privacy & Security / Share iPad Analytics / Share With App Developers, especially if you observed SEB crashes. We then receive anonymized crash reports.
Often a test link (send URL and if necessary login/password for a testing/demo account) or an SEB configuration file to reproduce the issue is helpful (remove SEB Quit and Admin passwords!) and compress the .seb file to ZIP to attach here.

**Comment by rataplanbe** [comment] 2023-12-12 19:11
Attachment
[TEST_SEB.seb.zip](https://github.com/SafeExamBrowser/seb-mac/files/13652307/TEST_SEB.seb.zip)

**Comment by danschlet** [comment] 2024-01-09 14:23
Apple confirmed that there is a bug in iOS/iPadOS up to 17.2 which causes crashes when playing videos in WKWebView (or when performing other different multi-media activities) while the app is in AAC Assessment Mode. They implemented a probable fix in iOS 17.3 Beta 2 and iPadOS 17.3 Beta 2, but unfortunately that beta seed has been temporarily withdrawn because of another issue in it.

There is a workaround:
- Disable Guided Access in Accessibility settings
- Remove (MDM) payloads enabling apps to activate ASAM (the managed version of AAC)
- If you ever used Classroom to lock the device, you have to reset its settings (Settings —> General —> Transfer or Reset —> Reset —> Reset all Settings)

**Comment by danschlet** [comment] 2024-01-10 00:02
For me iPadOS 17.3 Beta 3 solves the crashes when playing video.

**Comment by danschlet** [comment] 2024-02-07 16:02
The same apples to the final release version of iOS 17.3.

**Comment by danschlet** [comment] 2024-02-07 16:02
The issue seems to be fixed in the final release of iOS 17.3.

**Closed by danschlet** 2024-02-07 16:02 UTC
Labels: Fixed in specific OS version
