### ISSUE TITLE
SEB 3.1 crashes on iOS when configured via MDM (JAMF)

### ISSUE THREAD

**Issue by seangirard** [SafeExamBrowser/seb-mac#225] opened 2022-07-19 19:09 UTC
I know this is not a lot to go on, but hoping for some advise. We have used JAMF to configure SEB in the past, but did not use SEB during COVID-19 (so have not tested for some releases) and are doing some testing and validation of our procedures prior to fall term. 

When launching SEB on an iPad configured via plist in JAMF, SEB shows a blank (white) screen and then exits with no message. This happens on a "stock" configuration profile exported from SEB installed through the App Store. We have experimented with some of the settings (primarily related to single app mode as well as trying different start url).

I guess this is partly a bug report and partly a request for any troubleshooting suggestions. I will attach one of the plists we have tested here, in case that is helpful.
[esfcom-seb-2.plist.zip](https://github.com/SafeExamBrowser/seb-mac/files/9144002/esfcom-seb-2.plist.zip)

**Comment by danschlet** [comment] 2022-07-20 08:54
I'll try to reproduce this issue, as it seems it happens with any configuration, it might be a general problem with MDM configuration in SEB 3.1. I think we tested it last with SEB 3.0 and were not aware of changes in this code in 3.1, but probably some change broke MDM configuration in this version.

**Comment by markstisd956** [comment] 2022-10-17 20:33
I am having the same issue.  We are using Securly MDM and I have tried making the plist file in the app (3.1.1) and having Securly push the config to iPads. I have tried on both iPad Pros (5th gen 12.9 inch) and regular iPads (9th gen) Same issue as OP, blank screen then crash to home screen with no error message.  Using the same config but saving the file as a SEB file instead does work if I place it on a web server and have the iPads visit the link, but when deploying the plist file via MDM, which would be optimal, it does not work.  I agree with OP that it seems to crash with any config as I tried several different combinations of settings as well to see if one particular setting was causing it, but have not gotten a single plist file to work via MDM.  Looks like it is not just JAMF.

**Comment by danschlet** [comment] 2022-10-18 07:09
Ok, I tried it with the plist provided by @seangirard (don't know if I missed to do that before), and it also crashed. I found the issue and it will be fixed in the next release (3.1.2).

As a workaround in the meantime you can remove the entry for prohibitedProcesses from your settings (use a text editor or similar). These are anyways irrelevant for the iOS version.

`	<key>prohibitedProcesses</key>
	<array>
		<dict>
...
		</dict>
		<dict>
...
		</dict>
...
	</array>
`

**Comment by RonHassan** [comment] 2023-07-05 15:52
I'm having the same issue using SEB 3.2 and MDM (Mosyle).  SEB opens momentarily to a white screen and then crashes.  The config file worked fine when loaded from a webserver.

**Comment by danschlet** [comment] 2024-03-13 16:13
This should be fixed since SEB 3.3.

**Closed by danschlet** 2024-03-13 16:13 UTC
Labels: in development
