### ISSUE TITLE
Test didn't work with moodle 3.9

### ISSUE THREAD

**Issue by SebastianZiegler** [SafeExamBrowser/seb-mac#61] opened 2020-07-08 07:48 UTC
Hi,

one of our students reported that she cannot start our Test.

I tested this 2 week ago with version 2.1.5 pre2 with the same test without problems. She had 2.1.5 pre3 installed, I can check this on my device today evening. Maybe some changes in 2.1.5 pre3 cause this issue?

![IMG_9425](https://user-images.githubusercontent.com/2564530/86892171-2f8aae80-c100-11ea-9d91-26534dedcc4e.jpg)

**Comment by danschlet** [comment] 2020-07-08 10:43
Well, as I can see in the screen shot, SEB was started with an exam config (saved with "starting an exam"), they navigated to the quiz (or it was set as Start URL in those exam settings) and as those settings were not identical to the ones set for the quiz in Moodle 3.9 (with the new SEB integration), Moodle tries to load the exam settings configured for that quiz. This won't work in the current Mac version (currently on the iOS version can reconfigure from one exam settings to another, if configured accordingly). 

Are you sure that nothing changed besides the SEB version? Was the testing 2 weeks ago with the same Moodle version and quiz?

One possible scenario I could imagine: If you're using the Browser Exam Key in your quiz settings (which is still possible with the new Moodle-SEB integration, depending on how you set up the quiz), you need to add the Browser Exam Key for SEB 2.1.5pre3, as that one is different than the one in SEB 2.1.5pre2. 

If you're using the Config Key calculated by Moodle, it should still work same in pre3 as in pre2. My test quizzes in Moodle 3.9 work correctly both with pre2 and pre3. I would need test access to the quiz to figure out what went wrong (or maybe the log files).

**Comment by SebastianZiegler** [comment] 2020-07-10 07:19
Tested yesterday. And on my device with pre3, I had the same issue. After downgrading to pre2 everything is fine. I send you login information to a test where you can check.

**Comment by danschlet** [comment] 2020-07-10 07:32
Yes, please do that. I intend to release the final version of 2.1.5 very soon now, so it would be good I could try it before.

**Comment by merrill-oakland** [comment] 2020-07-10 18:44
When can Pre3 be downloaded? I can try it out against out Moodle 3.9 site.

**Comment by merrill-oakland** [comment] 2020-07-10 18:55
I built pre3 from master and am seeing the same thing. If I load into 2.1.5pre2, it works fine, if I load 2.1.5pre3 I get:

> Loading New SEB Settings Not Allowed!
> SEB is already running in exam mode and it is not allowed to interrupt this by starting another exam. Finish the exam and quit SEB before starting another exam.

And I can switch back and forth, pre2 always works, pre3 does not. 

I'm not sure where the Browser Exam Key is set. I'm a moodle dev and admin, but new to SEB, so I'm happy to provide whatever you may need.

**Comment by danschlet** [comment] 2020-07-10 22:13
Earlier today I removed 2.1.5pre3, after I was able to reproduce the issue. I found the reason for this bug, it's actually not directly related to the calculation of the Config Key (which was used in this Moodle 3.9 setup) and also not to the Browser Exam Key. I just committed the fix to master.

**Comment by danschlet** [comment] 2020-07-10 22:14
I will provide a new testing build latest on Monday.

**Comment by danschlet** [comment] 2020-08-28 17:46
In the end we jumped over the version 2.1.5, because we had to prioritize the prohibited processes feature. Now we finalized SEB 2.2 for macOS, which includes all fixes for the Config Key and should work properly with Moodle 3.9:
https://github.com/SafeExamBrowser/seb-mac/releases/tag/2.2

The release information is not yet ready, we will update that, the manual and information about how to use the prohibited processes feature properly early next week.

**Closed** 2020-08-28 20:17 UTC
