### ISSUE TITLE
SEB not working (old), crashing on iOS 17 (new issue)

### ISSUE THREAD

**Issue by AnnePH** [SafeExamBrowser/seb-mac#321] opened 2023-09-19 05:37 UTC
We are using Safe Exam Browser in our quizzes but when some of our iPad updated to iOS 17.0 this error was produced:
![image](https://github.com/SafeExamBrowser/seb-mac/assets/145423889/515407b4-271d-4cbe-a83b-49b42b0616bc)
Does anyone have the same experience? Do we have a workaround for it? We cannot downgrade our iPads though...

Your feedback and suggestion is highly appreciated.

Thanks! 😊

**Comment by danschlet** [comment] 2023-09-19 06:26
We are waiting for Apple App Store review to approve the SEB 3.3 update which will run on iOS 17 without having to change settings. For now you can either change the setting below manually in your SEB settings or use the SEB 3.3 release candidate version [using TestFlight with this link](https://testflight.apple.com/join/egxLmc4j). 

You can include or change the setting allowiOSBetaVersionNumber with the value 17 in an unencrypted SEB configuration file:
```
	<key>allowiOSBetaVersionNumber</key>
	<integer>17</integer>
```
Then the current version will run on iOS 17 (by now this should be without risk).

**Comment by AnnePH** [comment] 2023-09-19 06:51
I appreciate the fast response on this. I will let you know if this works.

**Comment by jjack2003** [comment] 2023-09-22 15:32
We have some students who have updated to iOS 17, and cannot open tests in the browser.  It brings up the red screen.  We verified the student was on version 3.3 through our MDM, but after a hard restart, we are still having the issue.  Any thoughts or suggestions.

**Comment by danschlet** [comment] 2023-09-22 15:39
There seems to be an issue on specific devices using iOS 17. Frequent crashes occur when in AAC and clicking into or starting to enter text in any text field (alerts, text fields in other app UI, text fields on a website displayed in WKWebView or UIWebView). This doesn't happen with the same version of SafeExamBrowser running on iOS 16.6.1 or iOS 15.6.1.

It also doesn't happen on other devices. Until now I tried it on four iPads, and it seems it happens on iPads with cellular, not on iPads with WiFi only. I reported this to Apple, as it might be an iOS 17 issue.

Can you try to find out if students with these issues have iPads with Cellular? Or in general on which devices it happens?

**Comment by danschlet** [comment] 2023-09-22 15:42
Step-by-step instructions to reproduce:
- Install SafeExamBrowser 3.3 from the App Store. 
- In the field "Enter the URL of an institution which supports SEB" enter "let.ethz.ch" (without quotation marks).
- Alternatively open the page https://safeexambrowser.org/exams/ in Safari and proceed as below.
- On the newly displayed page "Exam Portal" click on the first link SEB Demo Exam, confirm app self lock.
- Tap the quit button in the lower right
- Either SEB will crash immediately, otherwise in the alert asking for the quit password (which is in this case "quit") start typing.
- Observe if a crash is happening.

**Comment by jjack2003** [comment] 2023-09-22 15:43
All of our student iPads are wifi only.

**Comment by danschlet** [comment] 2023-09-22 15:56
Then it might be another reason, why it happens on some devices but not on others. For you, does it happen to all students which are updated to iOS 17?

**Comment by jjack2003** [comment] 2023-09-22 16:01
I have only heard from about 15, so far.   We 390/1500 updated to 17 at this time.  I will have to see how many more report the issue.  It may very intermittent.  I just set up a test device, newly enrolled with iOS 17 and version 3.3, it doesn't seem to be having the issues.  I am updating another device, just as a student would, and I will see how that one works.  I appreciate the quick responses.  I will keep you updated.

**Comment by danschlet** [comment] 2023-09-22 16:11
Thank you for keeping me updated. I've been trying to analyze this issue the last two days since we realized it. Somehow it didn't occur while testing on iOS 17 beta versions (or on the devices we used then).

**Comment by AnnePH** [comment] 2023-09-25 08:21
We also encountered a red screen, when during the exam, the student forcibly restarted the iPad. We resolved the red screen issue by inputting the quit password.

**Comment by rataplanbe** [comment] 2023-09-25 14:09
> Step-by-step instructions to reproduce:
> 
> * Install SafeExamBrowser 3.3 from the App Store.
> * In the field "Enter the URL of an institution which supports SEB" enter "let.ethz.ch" (without quotation marks).
> * Alternatively open the page https://safeexambrowser.org/exams/ in Safari and proceed as below.
> * On the newly displayed page "Exam Portal" click on the first link SEB Demo Exam, confirm app self lock.
> * Tap the quit button in the lower right
> * Either SEB will crash immediately, otherwise in the alert asking for the quit password (which is in this case "quit") start typing.
> * Observe if a crash is happening.

If I try this and I want to login in the exam, I have a crash. If I reopen SEB I have a red screen. If I want to put te word 'quit' in the textfield in the red screen, the app crashed. We are using IOS 17.0.1

**Comment by Basti8619** [comment] 2023-09-28 11:11
![Afbeelding (2)](https://github.com/SafeExamBrowser/seb-mac/assets/146340181/43577721-dfb2-4047-b77b-edd075b45fc7)
Just found this thread. Every iPad updated to iOS 17 now has SEB version 3.3 but none can use it with bookwidgets. They get this message. Something to do with settings? Never had any problems before on older iOS versions.

**Comment by danschlet** [comment] 2023-09-28 11:23
There is some iOS 17 bug involved, as there are devices with iOS 17 where it works perfectly, on other devices it crashes regularly, mostly when tapping or displaying text input fields. And on the same devices it doesn't happen with iOS 16 or 15. So this is some mysterious combination of iOS 17 and some device settings or similar. We're trying to find out what we can do in SEB to prevent this iOS 17 issue crashing SEB.

**Comment by rataplanbe** [comment] 2023-09-28 12:31
> ![Afbeelding (2)](https://user-images.githubusercontent.com/146340181/271263387-43577721-dfb2-4047-b77b-edd075b45fc7.jpg)
> Just found this thread. Every iPad updated to iOS 17 now has SEB version 3.3 but none can use it with bookwidgets. They get this message. Something to do with settings? Never had any problems before on older iOS versions.

What happens if you do an hard reset on the device? Normally, the message is gone. We can run Bookwidgets, but the question type 'Textfield' don't work.

**Comment by Basti8619** [comment] 2023-09-28 12:42
> What happens if you do an hard reset on the device? Normally, the message is gone. We can run Bookwidgets, but the question type 'Textfield' don't work.

I will try it out with a test tablet. Can hardly reset over a 1000 tablets though. Hoping on a fix!

**Comment by danschlet** [comment] 2023-10-03 23:32
On one of my devices this issue seems to no longer to happen after updating it to iOS 17.1 Beta 2. Maybe someone can confirm that as well.

**Comment by Basti8619** [comment] 2023-10-06 09:16
I tested SEB on several iPads. 2 for each.

The ones on 17.0 had no problems.

The ones on 17.1:
1 has no problem.
the other couldnt open SEB. After reinstalling SEB it could but when i touched a textfield it crashes.

The ones on 17.2:
1 has no problem.
the other couldnt open SEB. After reinstalling SEB it could but when i touched a textfield it crashes.

I assume this is the known issue. When can we expect some news?

**Comment by danschlet** [comment] 2023-10-06 09:32
I now got feedback from Apple that they found the bug actually responsible for this. It should be fixed in a later iOS 17.1 beta version. 

There was a related bug in Guided Access which is already fixed in the current iOS 17.1 beta. Maybe this fix makes the other issue appear less often. 

But we will have for the full fix in iOS 17.1.

**Comment by Basti8619** [comment] 2023-10-06 11:19
> I now got feedback from Apple that they found the bug actually responsible for this. It should be fixed in a later iOS 17.1 beta version.
> 
> There was a related bug in Guided Access which is already fixed in the current iOS 17.1 beta. Maybe this fix makes the other issue appear less often.
> 
> But we will have for the full fix in iOS 17.1.

Superb, thank you!

**Comment by danschlet** [comment] 2023-10-16 09:13
Ok, so in the meantime we found the likely reason why it these crashes happen only on some devices and not on others: If Guided Access is enabled (iOS Settings / Accessibility / Guided Access), then these crashes happen in SEB with iOS 17 on our test devices (even though Guided Access itself is not being used with SEB).

Apple fixed the issue in iOS 17.1 (developer?) beta 3.

@jjack2003 @Basti8619 @rataplanbe can you confirm that on the devices these crashes happen Guided Access is enabled in Settings? Do they still happen when you disable Guided Access. This is what I confirmed on two test devices.

If this is reason is confirmed, then you can either wait for iOS 17.1, install beta 3 or disable Guided Access for the meantime.

**Comment by Basti8619** [comment] 2023-10-17 09:19
> Ok, so in the meantime we found the likely reason why it these crashes happen only on some devices and not on others: If Guided Access is enabled (iOS Settings / Accessibility / Guided Access), then these crashes happen in SEB with iOS 17 on our test devices (even though Guided Access itself is not being used with SEB).
> 
> Apple fixed the issue in iOS 17.1 (developer?) beta 3.
> 
> @jjack2003 @Basti8619 @rataplanbe can you confirm that on the devices these crashes happen Guided Access is enabled in Settings? Do they still happen when you disable Guided Access. This is what I confirmed on two test devices.
> 
> If this is reason is confirmed, then you can either wait for iOS 17.1, install beta 3 or disable Guided Access for the meantime.

Seems to be working. Have yet to confirm on multiple devices.

Thanks for this solution.

**Closed** 2023-11-27 10:34 UTC
Labels: Fixed in specific OS version

**Comment by jjack2003** [comment] 2024-02-07 14:16
Is anyone else having compatibility issues with IOS 17.3?
![Image](https://github.com/SafeExamBrowser/seb-mac/assets/145788902/2880a220-0951-4b87-bf1e-14bb6cd93286)

**Comment by azzazz280** [comment] 2024-04-17 15:09
![image](https://github.com/SafeExamBrowser/seb-mac/assets/130978347/cae35376-b00b-454c-ab03-07a5d814832e)
