### ISSUE TITLE
Crash on MacBook Pro - Sierra

### ISSUE THREAD

**Issue by dkummer63** [SafeExamBrowser/seb-mac#182] opened 2022-01-31 09:47 UTC
Today I was able to reproduce the mistake on another mac and can give you more details. I first installed Version 2.3.2 and it crashed the first time the program started. Then I deleted the program, installed Version 3.0 and it crashed again and the red window was closed so fast, that I could not fill in the exit password. 
I tried different things to totally delete the programm and reinstall it, but nothing worked. 
 
It is a MacBook Pro 12,1; MacOS Sierra, Vers. 10.12.6; Core i5; 
I attach the reportfile and hope, that you can help. We plan the final exam with the computers of the students and unfortunaltely many of them use Mac...
[Systembericht_27-1-2022.zip](https://github.com/SafeExamBrowser/seb-mac/files/7948653/Systembericht_27-1-2022.zip)

![vlcsnap-2022-01-27-08h59m14s656](https://user-images.githubusercontent.com/89595743/151317029-5d7be215-1355-4f87-a2d8-3cd089917f18.png)
![vlcsnap-2022-01-27-09h00m36s173](https://user-images.githubusercontent.com/89595743/151317033-2c590970-c59e-4a3a-853b-56e3f413b7e5.png)
![vlcsnap-2022-01-27-09h01m02s206](https://user-images.githubusercontent.com/89595743/151317034-1107197f-29f7-427b-9486-09b511bf63c9.png)

**Comment by danschlet** [comment] 2022-01-31 10:04
I'm sorry but this doesn't really help, please test if the issue still happens in the latest preview of version 3.1 (currently 3.1pre7). I fixed many issues in 3.1, amongst that the red lock screen issue as far as I remember (it still needs more testing). Also quite some reasons for crashes, although I did only brief testing on macOS 10.11 and 10.13, not 10.12.
If the issue still happens in 3.1 (or for me to have a hint what it could have been) I would need the full crash report (displayed after SEB crashed or in Console.app under Crash Reports).

Thanks.

**Comment by dkummer63** [comment] 2022-01-31 10:33
The error also appears with version 3.1 for Mac. The error log is attached. The link leads to an online Word page where the students are supposed to write the exam. The other tested versions of MacOS have worked so far except Sierra
[Process_fail_MacOS_10.12.6 Sierra.docx](https://github.com/SafeExamBrowser/seb-mac/files/7970044/Process_fail_MacOS_10.12.6.Sierra.docx)
.

**Comment by danschlet** [comment] 2022-01-31 13:59
This seems to be a crash of the web engine ("Crashed Thread:  15  WebCore: Worker"). Probably caused by the older WebKit version which macOS Sierra uses. If the classic WebView was used, this might be fixed by changing the used SEB settings to use the modern WebView. But maybe the crash happens also in the modern WebView. You can test which WebView type is used (from SEB 3.1pre7) by trying if you can pinch-to-zoom the page with a trackpad (only the modern WebView supports pinch-to-zoom), unless page zoom was disabled in SEB settings. In the according SEB log you can also see which WebView is used (search for "Opening modern WebView" or "Opening classic WebView").

**Comment by danschlet** [comment] 2022-01-31 14:05
Btw. "modern" or "fancy" web applications usually are only compatible with quite recent web browsers. SEB on Mac/iOS uses the WebKit browser engine which is provided by the according macOS or iOS version, that means that such web applications might not run on older macOS or iOS versions. To be safe, anyways only the three most recent macOS versions should be used, because Apple only provides security updates to those (so currently macOS 10.15, 11 and 12). 
Compatibility with Safari on that macOS version isn't a guarantee SEB will work as well, a) unless the modern WebView is used, b) the web application doesn't use features which are available only in Safari and not in the OS-provided WebView and c) Safari uses an embedded WebKit version, which would be newer than the version provided by macOS to third-party-applications like SEB.

**Closed** 2022-03-07 12:57 UTC
Labels: feedback required, web application issue
