### ISSUE TITLE
CMD+F not working in PDFs

### ISSUE THREAD

**Issue by xyuping21** [SafeExamBrowser/seb-mac#308] opened 2023-06-15 12:08 UTC
ver 3.2.5 on macOS's last version.
when opening a pdf that was uploaded to moodle, pressing CMD+F will open a search box but won't show results for the word searched.

notice the CMD+F work perfectly on the moodle's webpage itself.

that's a critical for our faculty (law, which has lot of texts in exams).

best.

**Comment by danschlet** [comment] 2023-06-16 08:27
Closed as duplicate of https://github.com/SafeExamBrowser/seb-mac/issues/299

**Please ALWAYS check first if there is a similar issue open.**

**Closed by danschlet** 2023-06-16 08:27 UTC
