### ISSUE TITLE
Inline PDF do not take full size of window

### ISSUE THREAD

**Issue by acamacho-unige** [SafeExamBrowser/seb-mac#354] opened 2023-12-22 09:26 UTC
**Describe the bug**
When using SEB 3.3 on MacOS (recent versions, and recent mac computers) we saw a strange behaviour in multiple computers. As you can see in the video bellow, PDF files opened in a new window did only take a part of the avalaible space.
This makes viewing those file impossible on those computers, and seemed to happen with PDF viewer, doesn't matter where the PDF's came from.

**To Reproduce**
1. Go on moodle platform, and click on a PDF file that does not trigger a download
2. A new page opens with PDF viewer, all functions are avalaible and functioning

**Expected behavior**
PDF should present in all the new window, and when resizing window that should change.
PDF viewer takes 100% of width, but only has a fixed height of a few hundred pixels.

**Screenshots**
See video

**Version Information**
Please complete the following information: 
 - OS: Mac OS 13 + 14
 - SEB Version 3.3

https://github.com/SafeExamBrowser/seb-mac/assets/114589068/a688ad6a-3933-4a93-b774-5ef1b5b08b02

**Comment by danschlet** [comment] 2023-12-22 21:43
Please provide a demo quiz where I reproduce that.

**Comment by acamacho-unige** [comment] 2024-01-02 08:33
Hi,

We can send you a quiz, but the files were available through Moodle in a "file folder" activity.
Files open in a new window.

But we can not reproduce this error on our Mac equipment (Intel Macbooks Pro).

Are you sure the quiz (moodle mbz) helps you ?

Thanks

**Comment by danschlet** [comment] 2024-01-08 16:18
Well I would need any URL or SEB config where I can easily and reliably reproduce the issue, especially when you say you couldn't reproduce it on your Mac equipment. Not sure I will be able to reproduce it with any Moodle quiz and any PDF. I can try, but I will hardly have time to do trial-and-error before the next release.

At least the SEB log files might give me some hints, but I guess you don't have those.

Since SEB 3.x it would always be important to check, if the modern or classic WebView was used. You can do that with pinch-to-zoom on the trackpad (works on Mac only in modern WebView if zooming wasn't explicitly disabled in settings) or check in SEB log file.

**Comment by acamacho-unige** [comment] 2024-05-22 13:59
Hi Daniel,

After more tests we can reproduce the error without problem now :

- Moodle version : 4.1.9+
- SEB version : 3.3.2
- Mac OS version : Last - Sonoma (everything up to date)

When using a **mod_folder** in Moodle, PDF files inside are showed inline with PDF.js library but have a problem in resolution (as you can see in the pictures).

When uploading PDF files to a **mod_block**, PDF files inside open in a new window and are showed inline with PDF.js library in full size without any problem.

We checked with same PDF file, and can reproduce that.

![mod_folder](https://github.com/SafeExamBrowser/seb-mac/assets/114589068/471f6c00-557c-4f70-8a44-c96c910db904)
![block_html](https://github.com/SafeExamBrowser/seb-mac/assets/114589068/72ab4d4a-b0ae-4984-be06-447080143f7d)

Do you know where we could start looking ?
Could it be a problem from Moodle theme ?

(We are using a very lightly modified version of official theme of Moodle 4)

**Comment by danschlet** [comment] 2024-05-22 14:11
I'm not familiar with mod_folder or mod_block (I'm not a Moodle specialist). I would need some test/demo quiz/course (doesn't have to be protected with SEB as long as the issue occurs also without "Use Safe Exam Browser – Yes") where I can see and debug that.

Can you provide me with such a course and a login? I cannot set that up in another Moodle on my own, I have way to much other open work.

**Comment by acamacho-unige** [comment] 2024-11-04 13:45
Using SEB 3.4b3 (on MacBookPro15,2 on Sonoma) and SEB 3.4 (Macbook Pro M2 Pro, on Sequoia) it seems that this issue regarding PDF files opening in a small part of the windows disappeared (or has been fixed) ...

**Comment by acamacho-unige** [comment] 2024-11-13 13:06
> Using SEB 3.4b3 (on MacBookPro15,2 on Sonoma) and SEB 3.4 (Macbook Pro M2 Pro, on Sequoia) it seems that this issue regarding PDF files opening in a small part of the windows disappeared (or has been fixed) ...

After a mock exam this week, it seems that this problem still exists on SEB 3.4 on MacOS computers.

**Comment by danschlet** [comment] 2024-11-15 13:29
There is an interesting comment here https://github.com/SafeExamBrowser/seb-win-refactoring/discussions/487#discussioncomment-9949125:

Adding comment for the Moodlers that will stumble upon this thread. To allow the PDF to be rendered by the browsers (win or mac) as described by @danschlet above. You need to make sure there are no "Force download of files" ticked (by default it is ticket for folders) in the moodle settings'.

**Comment by danschlet** [comment] 2024-12-02 16:16
Looks like this issue happened only in a specific minor/patch version of macOS Ventura and is fixed in the latest Ventura update (if I remember our discussion correctly @acamacho-unige). If so, we can probably close this issue?

**Comment by acamacho-unige** [comment] 2024-12-03 09:07
> Looks like this issue happened only in a specific minor/patch version of macOS Ventura and is fixed in the latest Ventura update (if I remember our discussion correctly @acamacho-unige). If so, we can probably close this issue?

That is right.
As soon as Ventura is updated to last minor version, an update (17.0 I think) for Safari is avalaible. If installed, this issue does not happen anymore.

We can close this for me.

**Closed** 2024-12-03 10:25 UTC
Labels: Fixed in specific OS version
