### ISSUE TITLE
MAC-PROHİBİTED PROCESS LOCKED SEB

### ISSUE THREAD

**Issue by sueda-v** [SafeExamBrowser/seb-mac#88] opened 2021-03-29 09:31 UTC
"When I start SEB, I am directed to odtuclass.metu.edu.tr, which is my exam
website. Then I log in but after a few minutes, I get this error on my
screen and I cannot go on. I have downloaded the right version of SEB (for
Mac) and my configuration is right. My computer used to start SEB properly
with no problems a couple of days ago. What is the problem and how can I
solve it?" 
![2da6090e-900a-4808-8539-62d93f4beb3e](https://user-images.githubusercontent.com/81356625/112816973-9c791680-908a-11eb-8191-05bdf9c464eb.jpg)

I use latest version 2.3.1 for MacOs . 
ps: I also downloaded and tried previous versions to fix the problem, but the result has not changed

**Comment by danschlet** [comment] 2021-03-29 09:55
This issue was fixed in SEB 2.3. Use the latest version 2.3.1: https://github.com/SafeExamBrowser/seb-mac/releases/tag/2.3.1

I guess you're using SEB 2.2.2 on macOS 11 Big Sur, there this problem was happening. 

Always first try the latest SEB version before posting an issue.

**Comment by sueda-v** [comment] 2021-03-29 10:02
> This issue was fixed in SEB 2.3. Use the latest version 2.3.1: https://github.com/SafeExamBrowser/seb-mac/releases/tag/2.3.1
> 
> I guess you're using SEB 2.2.2 on macOS 11 Big Sur, there this problem was happening.
> 
> Always first try the latest SEB version before posting an issue.

I use latest version 2.3.1 for MacOs .
ps: I also downloaded and tried previous versions to fix the problem, but the result has not changed

**Comment by danschlet** [comment] 2021-03-29 10:22
Ok, then I have to investigate it further. Did you try SEB 2.2.2 and the issue happened there as well?

Which macOS version are you using exactly (like 10.15.7 or 11.2.3?). Are you using a Intel Mac or one of the new Apple Silicon M1 Macs?

Please send me the SEB log files which can be found in the directory ~/Library/Logs/Safe Exam Browser/ (user home directory/Library/Logs/Safe Exam Browser/).

**Comment by danschlet** [comment] 2021-03-29 14:38
Ok, I think I found the reason for the issue, I can reproduce it on an Intel Mac running macOS 11.2.3. It worked on an Apple Silicon device (that was the pre-release Developer Transition Kit, which might have behaved differently than the current M1 Macs).

The issue can easily be tested if you have SEB settings where the menu bar is visible (that's the default setting) and by clicking on the system menu bar items: If the menu doesn't open and the menu bar content shortly disappears before appearing again, that's the same issue.

I uploaded a [version SEB 2.3.2](https://github.com/SafeExamBrowser/seb-mac/releases/tag/2.3.2) which fixes this, please test it and let me know if it works for you.

Thank you for reporting this issue!

**Comment by danschlet** [comment] 2021-04-21 09:58
Fixed in SEB 2.3.2

**Comment by francescaderi** [comment] 2021-05-19 14:36
@danschlet Hi, I have the same issue.
I use SEB 2.3.2 and macOS Catalina 10.15.7. If I read the log file I see that "Application Window Server is being force terminated because it isn't macOS system software!", so I suppose the issue is the same of sueda-v.
Thank you!
Francesca

**Comment by danschlet** [comment] 2021-05-19 14:46
Hi @francescaderi, 
Can you please post the log file? Window Server is macOS system software, so it shouldn't be terminated by SEB 2.3.2, also not on macOS Catalina. I guess you're using a standard Mac, are you aware of special security tools installed on that Mac? 
Maybe I'll be able to find out something from the log file.
Daniel

**Comment by francescaderi** [comment] 2021-05-19 15:12
Dear @danschlet ,
maybe I've found the problem. I have a MacBook Pro 2018 with two monitor linked with a docking station. I use DisplayLink software (https://www.displaylink.com/downloads/macos), version 1.2.0 to use both monitors with macbook 
monitor. The problem with SEB **doesn't happen** if quit DisplayLink. In this case one monitor turns off and I still have one monitor other than the macbook one.
I have attached the log, so you can investigate further: [org.safeexambrowser.SafeExamBrowser 2021-05-19 14-17 2.log](https://github.com/SafeExamBrowser/seb-mac/files/6509871/org.safeexambrowser.SafeExamBrowser.2021-05-19.14-17.2.log)
Thanks, bye,
Francesca

**Closed** 2021-08-04 12:47 UTC
Labels: bug, please test
