### ISSUE TITLE
Unable to access webcam

### ISSUE THREAD

**Issue by Elizabeth-Akerele** [SafeExamBrowser/seb-mac#401] opened 2024-05-06 21:27 UTC
**IMPORTANT**
Please always consult the documentation first before creating a bug report!
[Manual](https://safeexambrowser.org/macosx/mac_usermanual_en.html) (use find text in browser if you're looking for specific subjects)
[Release Notes](https://safeexambrowser.org/macosx/mac_release_notes_en.html) (for up-to-date information which might not be included in manual yet)

**Describe the bug**
I cannot access my webcam from safe exam browser I don't understand why, I have gone to my settings to allow access and on the settings of the browser , under browser I have allowed access also

**To Reproduce**

**Expected behavior**
I expect the webcam to show but it is not coming up

**Screenshots**
If applicable, add screenshots or a link to a video to help explain your problem.

**Version Information**
Please complete the following information: 
 - OS: [macOS14]
 - SEB Version [SEB 3.3.2]

**Additional Context**
Add any other context about the problem here: It is only happening to my mac but it is working on android OS

- Always send SEB log files (in directory ~/Library/Logs/Safe Exam Browser/ on Mac, use Settings app / SEB / Initiate Sending Logs to email log files to yourself and attach them here). 
- On iOS/iPadOS, please activate Settings / Privacy & Security / Share iPad Analytics / Share With App Developers, especially if you observed SEB crashes. We then receive anonymized crash reports. 
- Often a test link (send URL and if necessary login/password for a testing/demo account) or an SEB configuration file to reproduce the issue is helpful (remove SEB Quit and Admin passwords!) and compress the .seb file to ZIP to attach here.

**WITHOUT THIS INFORMATION WE USUALLY CANNOT ANSWER YOUR SUPPORT REQUEST!**

**Comment by danschlet** [comment] 2024-05-06 21:33
Duplicate of https://github.com/SafeExamBrowser/seb-mac/issues/400.

**Closed by danschlet** 2024-05-06 21:33 UTC
Labels: duplicate, invalid
