### ISSUE TITLE
Autofill: Copy-Paste from Contacts in SEB

### ISSUE THREAD

**Issue by AnnePH** [SafeExamBrowser/seb-mac#390] opened 2024-03-22 03:35 UTC
**Describe the bug**
During exams in SEB, particularly for essay questions, users have the option to long-press the answer field, enabling autofill, and then select either contacts or passwords to copy from. This allows the users to cheat on their exams.

**To Reproduce**
1. Open SEB
2. Long press on the text editor
3. Select Autofill
4. Select Contacts
5. Copy the notes on the contact information
6. Paste the answer to the answer field

**Expected behavior**
Disable the autofill function in SEB

**Screenshots**
please see the attached video for reference
https://github.com/SafeExamBrowser/seb-mac/assets/145423889/3a35d441-6e09-42bd-b6ea-fabba2205956

**Version Information**
Please complete the following information: 
 - IOS 17.3.1
 - SEB Version 3.3.2

**Additional Context**
We tried to simulate the issue in iOS 16.6.3 and the autofill option is not available.

**Comment by danschlet** [comment] 2024-03-22 09:12
Thank your for your report, this is a duplicate of https://github.com/SafeExamBrowser/seb-mac/issues/389. We're working on fixing it.

**Comment by danschlet** [comment] 2024-05-26 15:34
This was fixed in SEB 3.3.3 for iOS.

**Closed by danschlet** 2024-05-26 15:34 UTC
Labels: duplicate, in development
